collections:
  - services

title: Shoya Iwanami's note
email: iwanamishoya@gmail.com
email-at: iwanamishoya[at]gmail.com
phone: 092-802-4299
organizer: 岩波翔也
website: "https://shoyaiwanami.com"
author: Shoya Iwanami
affiliation: 九州大学数理生物学研究室
address: 〒819-0395 福岡市西区元岡744 九州大学伊都キャンパス ウエスト１号館C-911
description: >- # this means to ignore newlines until "baseurl:"
  生物学・数学などの研究に関することや、研究・教育を行う上で必要になったプログラミングなどの知識をメモ的に書いていきます。
keywords: 岩波翔也,岩波,翔也,九州大学,数理生物,免疫,理論免疫,Shoya Iwanami,Shoya,Iwanami,Kyushu University,Mathematical Biology,Immunology,Theoretical Immunology
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://note.shoyaiwanami.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
permalink: pretty
#google_analytics: UA-85165915-4
# google_maps: AIzaSyCmNAoJl7rD3i-J8BotDmoHjNO1O-ipa1w


markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
